In [2]:
import warnings

import requests
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

In [5]:
csv_file = "flipkart_smartphones_scraped_data.csv"
df = pd.read_csv(csv_file)
df.head(5)

,Product_Name,Brand,Rating,Price,Actual_Price,Page_number,RAM,Storage,Battery_Details,Camera_Details,Discount
0,"BOLTT EVO (Midnight Black, 64 GB)",BOLTT,4.3,"₹9,999","₹17,999",1,4 GB RAM,64 GB ROM,6000 mAh Lithium ion Battery,50MP + 2MP | 8MP Front Camera,44% off
1,"Mivi One 5G (Green, 128 GB)",Mivi,NaN,"₹12,999","₹21,999",1,4 GB RAM,128 GB ROM,6000 mAh Lithium Polymer Battery,50MP Rear Camera | 8MP Front Camera,40% off
2,"Samsung Galaxy F07 (Green, 64 GB)",Samsung,4.2,"₹11,999",NaN,1,4 GB RAM,64 GB ROM,5000 mAh Battery,50MP + 2MP | 8MP Front Camera,NaN
3,"BOLTT EVO (Berry Red, 64 GB)",BOLTT,4.3,"₹9,999","₹17,999",1,4 GB RAM,64 GB ROM,6000 mAh Lithium ion Battery,50MP + 2MP | 8MP Front Camera,44% off
4,"vivo T5 Lite 44W 5G (Twilight Shadow, 128 GB)",vivo,4.2,"₹20,499","₹33,999",1,4 GB RAM,128 GB ROM,6500 mAh Li-ion Battery,50MP + 0.08MP | 5MP Front Camera,39% off

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 990 entries, 0 to 989
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Product_Name     990 non-null    str
 1   Brand            990 non-null    str
 2   Rating           862 non-null    float64
 3   Price            990 non-null    str
 4   Actual_Price     893 non-null    str
 5   Page_number      990 non-null    int64
 6   RAM              961 non-null    str
 7   Storage          982 non-null    str
 8   Battery_Details  962 non-null    str
 9   Camera_Details   990 non-null    str
 10  Discount         880 non-null    str
dtypes: float64(1), int64(1), str(9)
memory usage: 85.2 KB

In [7]:
df.describe()

           Rating  Page_number
count  862.000000   990.000000
mean     4.298492    50.979798
std      0.201412    28.626453
min      3.500000     1.000000
25%      4.200000    26.000000
50%      4.300000    51.000000
75%      4.400000    76.000000
max      5.000000   100.000000

In [9]:
df1 = df.copy()
df1.head(5)

,Product_Name,Brand,Rating,Price,Actual_Price,Page_number,RAM,Storage,Battery_Details,Camera_Details,Discount
0,"BOLTT EVO (Midnight Black, 64 GB)",BOLTT,4.3,"₹9,999","₹17,999",1,4 GB RAM,64 GB ROM,6000 mAh Lithium ion Battery,50MP + 2MP | 8MP Front Camera,44% off
1,"Mivi One 5G (Green, 128 GB)",Mivi,NaN,"₹12,999","₹21,999",1,4 GB RAM,128 GB ROM,6000 mAh Lithium Polymer Battery,50MP Rear Camera | 8MP Front Camera,40% off
2,"Samsung Galaxy F07 (Green, 64 GB)",Samsung,4.2,"₹11,999",NaN,1,4 GB RAM,64 GB ROM,5000 mAh Battery,50MP + 2MP | 8MP Front Camera,NaN
3,"BOLTT EVO (Berry Red, 64 GB)",BOLTT,4.3,"₹9,999","₹17,999",1,4 GB RAM,64 GB ROM,6000 mAh Lithium ion Battery,50MP + 2MP | 8MP Front Camera,44% off
4,"vivo T5 Lite 44W 5G (Twilight Shadow, 128 GB)",vivo,4.2,"₹20,499","₹33,999",1,4 GB RAM,128 GB ROM,6500 mAh Li-ion Battery,50MP + 0.08MP | 5MP Front Camera,39% off

In [10]:
df1.columns

Index(['Product_Name', 'Brand', 'Rating', 'Price', 'Actual_Price',
       'Page_number', 'RAM', 'Storage', 'Battery_Details', 'Camera_Details',
       'Discount'],
      dtype='str')